version: '3.9'
services:
  discussion:
    image: "discussion:production"
    container_name: "discussion-prod"
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - BACKEND_PATH=${BACKEND_PATH}
    ports:
      - "10001:80"
    networks: 
      - proxynet
networks:
  proxynet:
    name: ozia_backend
