name: "Build and deploy Discussion project"
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["21.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        env:
          REACT_APP_BACKEND_PATH: ${{ secrets.BACKEND_PATH }}
        run: |
          cd discussion
          npm install
          npm run build --if-present
          mkdir artifact
          mv build artifact/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: discussion-build
          path: discussion/artifact
  deploy:
    name: Deploy Discussion on Shopify CDN
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["21.x"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: discussion-build
      - shell: bash
        run: |
          mv build/static/js/main*.js theme-app/extensions/ozia-chat/assets/script.js
          mv build/static/css/main*.css theme-app/extensions/ozia-chat/assets/stylesheet.css
      - name: npm install and deploy
        env:
          # Token from the Partner Dashboard
          SHOPIFY_CLI_PARTNERS_TOKEN: ${{ secrets.SHOPIFY_CLI_TOKEN }}
          COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          # .env content after a deploy
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
        run: |
          cd theme-app
          npm install
          npm run deploy -- -f  --source-control-url "$COMMIT_URL" --no-release
